# This file was generated by GoReleaser. DO NOT EDIT.
class Hoodieaf < Formula
  desc "Utility to you know if you need a hoodie or not."
  homepage "https://github.com/chayev/hoodieaf"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chayev/hoodieaf/releases/download/v0.2.0/hoodieaf-v0.2.0-macos-amd64.tar.gz"
    sha256 "3cf2d99969dfe56c4fd07092399fb292d97e791624f3dfc849c69c5fe1bb212c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chayev/hoodieaf/releases/download/v0.2.0/hoodieaf-v0.2.0-linux-amd64.tar.gz"
      sha256 "8edf64fe897fad738ec6df1c8f65576cdbdcc45cbf930ba9f20de9bad87d05f2"
    end
  end

  def install
    bin.install "hoodieaf"
  end

  test do
    system "#{bin}/hoodieaf", "help"
  end
end
