# This file was generated by GoReleaser. DO NOT EDIT.
class Hoodieaf < Formula
  desc "Utility to you know if you need a hoodie or not."
  homepage "https://github.com/chayev/hoodieaf"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chayev/hoodieaf/releases/download/v0.1.0/hoodieaf-v0.1.0-macos-amd64.tar.gz"
    sha256 "a253e09b340f4a89e4f1251635b6030555b620b88359dce6a0d8b4f1baa51230"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chayev/hoodieaf/releases/download/v0.1.0/hoodieaf-v0.1.0-linux-amd64.tar.gz"
      sha256 "32f5e963e396b262058fb7bc335548bf276e1fa69a2143b9819054d6a4cdb100"
    end
  end

  def install
    bin.install "hoodieaf"
  end

  test do
    system "#{bin}/hoodieaf", "help"
  end
end
