# This file was generated by GoReleaser. DO NOT EDIT.
class Odinlink < Formula
  desc "Utility for OneLink API."
  homepage "https://github.com/chayev/odinlink"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chayev/odinlink/releases/download/v0.2.0/odinlink-v0.2.0-macos-amd64.tar.gz"
    sha256 "951a7d19670c8f50337f6aae75db06b768afa20cc670ec67e1089904883cc267"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chayev/odinlink/releases/download/v0.2.0/odinlink-v0.2.0-linux-amd64.tar.gz"
      sha256 "0c7b202dbed1572fdf3397d0c79135686aba6e2cb679de11b5bc8c31ed84bf99"
    end
  end

  def install
    bin.install "odinlink"
  end

  test do
    system "#{bin}/odinlink", "help"
  end
end
