# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yurl < Formula
  desc "Universal Links / AASA File Validator."
  homepage "https://github.com/chayev/yurl"
  version "0.6.5"

  on_macos do
    url "https://github.com/chayev/yurl/releases/download/v0.6.5/yurl-v0.6.5-macos-amd64.tar.gz"
    sha256 "370210ec2d97e6cfc159b427e5cdeca85a6cb0675bcb703544d9da0ef0d1660a"

    def install
      bin.install "yurl"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Yurl
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chayev/yurl/releases/download/v0.6.5/yurl-v0.6.5-linux-amd64.tar.gz"
      sha256 "402785ca4da696fd33b2684a9a575670e21da35e90382beb676a94f355842e5d"

      def install
        bin.install "yurl"
      end
    end
  end

  test do
    system "#{bin}/yurl", "help"
  end
end
