# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yurl < Formula
  desc "Universal Links / AASA File Validator."
  homepage "https://github.com/chayev/yurl"
  version "0.7.0"

  on_macos do
    url "https://github.com/chayev/yurl/releases/download/v0.7.0/yurl-v0.7.0-macos-amd64.tar.gz"
    sha256 "f399a8926a24bcfe434e21f58e8d1d00440a62ac65e3fe48bf404964da20b52a"

    def install
      bin.install "yurl"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Yurl
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chayev/yurl/releases/download/v0.7.0/yurl-v0.7.0-linux-amd64.tar.gz"
      sha256 "3b8135993b262ff406e039f5b78b8b90d478ff28d695ea1b0a834e659a5e06fa"

      def install
        bin.install "yurl"
      end
    end
  end

  test do
    system "#{bin}/yurl", "help"
  end
end
