# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yurl < Formula
  desc "Universal Links / AASA File Validator."
  homepage "https://github.com/chayev/yurl"
  version "0.9.1"

  on_macos do
    url "https://github.com/chayev/yurl/releases/download/v0.9.1/yurl-v0.9.1-macos-amd64.tar.gz"
    sha256 "810c065fd443f3874d88a1d3162575e4a225e175652a2db729ac14365ccd1a91"

    def install
      bin.install "yurl"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Yurl
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chayev/yurl/releases/download/v0.9.1/yurl-v0.9.1-linux-amd64.tar.gz"
      sha256 "ebbcd3d18b2a03eef865064d9218e85177d5c568f89a9a23a0cda612112dbf82"

      def install
        bin.install "yurl"
      end
    end
  end

  test do
    system "#{bin}/yurl", "help"
  end
end
